### ISSUE TITLE
Harvest

### ISSUE THREAD

**Issue by abogawat** [junaid33/opensource.builders#102]
Time tracking platform

**Comment by mjjzf** [comment]
I did the translation on [Kimai](https://www.kimai.org/), which does good tracking and reports.
There is a [time tracker app for Nextcloud](https://apps.nextcloud.com/apps/timetracker), but it has not been to reliable, so I went back to my Kimai install.

**Comment by jcklpe** [comment]
Closing as duplicate of https://github.com/junaid33/opensource.builders/issues/74
