### ISSUE TITLE
Surge

### ISSUE THREAD

**Issue by talentlessguy** [junaid33/opensource.builders#106]
Static hosting for directories

**Comment by junaid33** [comment]
Does https://staticdeploy.io/ sound like an alternative?

**Comment by talentlessguy** [comment]
@junaid33 well, Surge is also [open source](https://github.com/sintaxi/surge)

**Comment by junaid33** [comment]
Oh I apologize, I thought you were looking for an alternative. I'll get Surge added as an alternative to Netlify then.

**Comment by jcklpe** [comment]
@talentlessguy  Hi, sorry, the closed source project should be in the title of the ticket, and the comments should provide open source alternatives. You have it backwards. Please edit to follow the form correctly.

**Comment by jcklpe** [comment]
closed as uncorrected
