### ISSUE TITLE
TeamViewer

### ISSUE THREAD

**Issue by OneNomad** [junaid33/opensource.builders#11]
Remote Desktop server/client

**Comment by suspended** [comment]
Apache Guacamole™

**Comment by OneNomad** [comment]
Seems like Linux centric. Windows RDP is an afterthought. Considering most, if not all machines I want to connect to, are, win-7 & win-10 machines, this is not a very useful solution.

**Comment by niiku** [comment]
Guacamole supports RDP. The last time I tried it worked pretty good.

**Comment by johnnyq** [comment]
Meshcentral - https://github.com/Ylianst/MeshCentral
Remotely - https://github.com/Jay-Rad/Remotely

We currently use MeshCentral and it has been working great works on mac linux and windows

**Comment by Acordovam** [comment]
AnyDesk

**Comment by FlickTheManual** [comment]
https://remmina.org/
