### ISSUE TITLE
Krita

### ISSUE THREAD

**Issue by talentlessguy** [junaid33/opensource.builders#113]
Digital Painting Program

**Comment by talentlessguy** [comment]
Alternative to Photoshop and Affinity Designer

**Comment by jcklpe** [comment]
@talentlessguy  Hi, sorry, the closed source project should be in the title of the ticket, and the comments should provide open source alternatives. You have it backwards. Please edit to follow the form correctly.

**Comment by jcklpe** [comment]
closed as uncorrected
