### ISSUE TITLE
Alternative to Slack

### ISSUE THREAD

**Issue by virtadpt** [junaid33/opensource.builders#12]
Matrix (https://matrix.org/)

**Comment by junaid33** [comment]
It seems Riot is the web client for Matrix. I have added Riot since Matrix is more the API correct?

**Comment by virtadpt** [comment]
That is correct, yes.

**Comment by Zer0t3ch** [comment]
@junaid33 Might be prudent to include next to or replace Riot with Synapse. (the backend server implementation of Matrix)

Selfhosting the client is great, but when most people are not going to be self-hosting the app they use on their phone to connect, the selfhosting of a federated server seems like the more "intended" thing to host.

**Comment by virtadpt** [comment]
Agreed.  Riot is not an all-in-one solution, it's a front-end.  Useless without Synapse, Dendrite, or any other Matrix implementation on the back end.
