### ISSUE TITLE
Alternatives to Facebook

### ISSUE THREAD

**Issue by virtadpt** [junaid33/opensource.builders#15]
Mastodon (https://github.com/tootsuite/mastodon)

Epicyon (https://gitlab.com/bashrc2/epicyon)

Pleroma (https://git.pleroma.social/pleroma/pleroma)

**Comment by junaid33** [comment]
Unfortunately, the app only supports Github repos for now so I've added Mastodon. I'll support Gitlab and other soon so I'll the other 2 then.

**Comment by alexanderadam** [comment]
But you shouldn't close the issue then‽
I mean: it is not _fixed_ but rather _dependent_ from your GitLab-support feature, right?
