### ISSUE TITLE
Zoom / Skype

### ISSUE THREAD

**Issue by nrgapple** [junaid33/opensource.builders#157]
Desktop screen sharing

**Comment by pubmania** [comment]
and mobile screen sharing too... zoom does it best and no other software that I know of comes close to it let alone open source software.

**Comment by jcklpe** [comment]
Jitsi. Also worth checking out bigbluebutton and NextCloud Talk.

**Comment by rosa2** [comment]
For bigger needs https://bigbluebutton.org/

**Comment by jcklpe** [comment]
closed as dupe: https://github.com/junaid33/opensource.builders/issues/56
