### ISSUE TITLE
S3

### ISSUE THREAD

**Issue by virtadpt** [junaid33/opensource.builders#16]
Object storage

**Comment by tohjustin** [comment]
Ceph (http://ceph.com, Repo: https://github.com/ceph/ceph)

Minio (https://min.io, Repo: https://github.com/minio/minio)

Swift (https://www.swiftstack.com/product/open-source/openstack-swift, Repo: https://github.com/openstack/swift)

**Comment by junaid33** [comment]
Added

**Comment by virtadpt** [comment]
Thanks, @tohjustin.  I was going to add a couple of these once the S3 category was up, you beat me to it.
