### ISSUE TITLE
Please consider renaming it to FREE and open source...

### ISSUE THREAD

**Issue by ImaCrea** [junaid33/opensource.builders#166]
Hi there,
thanks a lot for this great initiative of yours. This website is definetely a great ressource. I'll come to it regularly but let me offer here a suggestion : add "free" to the project.

Free software and Open source software are not really the same thing as you may know. It is important that people do not forget about it. There's a great difference between using GPL license and Apache and else. In one case, everybody make sure the ressource stays a common for everyone. This is how we stay free as citizens, and in these current times ensuring that it crucial.

Hope you'll consider that suggestion,
cheers.

**Comment by alexanderadam** [comment]
The list also contains non-free and non-open source Software (see also [23](https://github.com/junaid33/opensource.builders/issues/23) and [35](https://github.com/junaid33/opensource.builders/issues/35)).

So adding "free" to it, would be lying _even more_. :wink:

**Comment by ImaCrea** [comment]
Didn't notice that. Yes it's also important. But I would say that to do things well and aligned with the author's vision explained in the "about" section, these non-free and non-open software should be removed AND title copywriting should be reviewed in order to mention these are **Free and Open Source Softwares.**

What do you think?

**Comment by alexanderadam** [comment]
I, personally, think it would be great to have an overview about FOSS. **But** this is **not** the view of the author.
Because for the author just source code availability is important. Not the freedom of the source.

Or [how he put it in an issue where someone actually wanted to remove non-free software](https://github.com/junaid33/opensource.builders/issues/22#issuecomment-592084414):

> this app can include _any_ application that has the source-code available and can be self-hosted.

As you can see, a free license is not mentioned at all. :wink:

**Comment by ImaCrea** [comment]
Well let's see what he thinks about it. Maybe he doesn't know about free software? 

Here's some help: https://www.gnu.org/philosophy/open-source-misses-the-point.en.html :)

**Comment by fire** [comment]
So would Unreal Engine be acceptable here because it's clearly source available and free when you don't make money.

I disagree, but I also work on Godot Engine, an open source and free competitor.

**Comment by ImaCrea** [comment]
Not sure what you're talking about @fire

**Comment by ImaCrea** [comment]
I'm talking about "free software" here. "free" as in "free speech" not "free beer". You know... GPL license..

**Comment by fire** [comment]
Referring to https://github.com/junaid33/opensource.builders/issues/22#issuecomment-592084414 aka Sentry.

**Comment by fire** [comment]
Adding the word free is confusing, while Open Source has a very detailed definition.

I've seen programs like Google Summer of Code, require all projects to be under an OSI license.

https://opensource.org/licenses

> What are the eligibility requirements for a mentoring organization?

> To be eligible to participate as a mentoring organization, you must be a group running an active free/open source software project, e.g. BRL-CAD. The project does not need to be a legally incorporated entity. Mentoring organizations must have already produced and released software under an Open Source Initiative approved license and have at least two contributors to serve as organization administrators and/or mentors for the entire program in order to participate in the program.

https://developers.google.com/open-source/gsoc/faq

**Comment by ImaCrea** [comment]
The whole difference is copyleft. Free software with GPL licenses are with copyleft whereas most open source license don't ensure that. Learn about copyleft, it's very important if we want to keep code open and editable for all. Without that guarantee, we keep moving into a world where a wall separate developers and users, and this is not acceptable.

**Comment by fire** [comment]
There are philosophical arguments that are well established, but I think we can agree that both copy left and non copyleft OSI licenses are better than proprietary licenses.

I’m dropping out from this conversation.
