### ISSUE TITLE
Alternatives to GitHub

### ISSUE THREAD

**Issue by tohjustin** [junaid33/opensource.builders#17]
Gogs (https://gogs.io/, Repo: https://github.com/gogs/gogs)

Phabricator (http://phacility.com/phabricator/, Repo:  https://github.com/phacility/phabricator)

Sourcehut (https://sourcehut.org/, Repo: https://git.sr.ht/~sircmpwn/?search=sr.ht)

**Comment by junaid33** [comment]
Added
