### ISSUE TITLE
Sentry is no longer open source

### ISSUE THREAD

**Issue by arthurlutz** [junaid33/opensource.builders#173]
https://blog.sentry.io/2019/11/06/relicensing-sentry

**Comment by alexanderadam** [comment]
[I have the feeling that you didn't consider the search, didn't you?](https://github.com/junaid33/opensource.builders/issues/22) :wink:

**Comment by arthurlutz** [comment]
Sorry for the noise, I only searched in open issues, forgot to check the closed ones.

**Comment by alexanderadam** [comment]
Easy, by the way I'm not the maintainer and I also tend to have a different opinion than the maintainer, on what OSS means.
