### ISSUE TITLE
Log Rocket (error tracking)

### ISSUE THREAD

**Issue by arthurlutz** [junaid33/opensource.builders#174]
https://glitchtip.com/

**Comment by jcklpe** [comment]
@arthurlutz  Hi, sorry, the closed source project should be in the title of the ticket, and the comments should provide open source alternatives. You have it backwards. 

I see you have made a pull request to merge this in with Log Rocket, so I will go ahead and change the title, and set it as a request. Hopefully at some point whoever is doing code review will be able to check back in on that merge. Thank you for contributing!
