### ISSUE TITLE
Photoshop

### ISSUE THREAD

**Issue by kush-daga** [junaid33/opensource.builders#191]
Photo editing application

**Comment by jcklpe** [comment]
Sadly there isn't really a great open source alternative for this. The most direct analog is GIMP which hasn't really improved it's UI or features in like a decade. 

There's a recent offshoot/rebranding of GIMP called Glympse which seems promising. 

And Krita is almost feature par with photoshop if you're just doing digital painting.

**Comment by jcklpe** [comment]
Closed as duplicate of: https://github.com/junaid33/opensource.builders/issues/112
