### ISSUE TITLE
SonarQube

### ISSUE THREAD

**Issue by abidev** [junaid33/opensource.builders#192]
Code and Security Quality Analyser

**Comment by jcklpe** [comment]
@abidev  Thank you for the contribution. 

I need you to make one tiny correction.  It appears the SonarQube is already open source. The closed source project should be in the title of the ticket, and the comments should provide open source alternatives. You have it backwards. Please edit to follow the form correctly.

**Comment by jcklpe** [comment]
Closed with no correction
