### ISSUE TITLE
Google Maps (transit / mapping applications)

### ISSUE THREAD

**Issue by Bilouks** [junaid33/opensource.builders#207]
Hello, 
You could add open source travellers information softwares to your Opensource builders list, couldn't you? 
- Navitia Trip Planner https://github.com/CanalTP/navitia and www.navitia.io API and SDK
- Open Trip Planner https://github.com/opentripplanner
Different than Google Transit/ Goocle Maps or Citymapper for example.
Best regards.

Bertrand Billoud
Kisio Digital

**Comment by jcklpe** [comment]
@Bilouks  What would be an example of a closed source alternative?

**Comment by jcklpe** [comment]
@Bilouks  sure thing, sounds good. I will change the issue title to better reflect the intended format of these issues.

**Comment by jcklpe** [comment]
Actually closed as duplicate to this: https://github.com/junaid33/opensource.builders/issues/181
