### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by bilalghalib** [junaid33/opensource.builders#215]
video conferencing with breakout rooms

**Comment by binc0** [comment]
https://jitsi.org

**Comment by jcklpe** [comment]
Can second Jitsi. Also worth checking out bigbluebutton and NextCloud Talk.

**Comment by jcklpe** [comment]
Duplicate of: https://github.com/junaid33/opensource.builders/issues/157

**Comment by jcklpe** [comment]
Closing as duplicate: https://github.com/junaid33/opensource.builders/issues/157
