### ISSUE TITLE
Microsoft Office

### ISSUE THREAD

**Issue by wilfried18** [junaid33/opensource.builders#216]
Word processing software 
LibreOffice

**Comment by jcklpe** [comment]
My recommendation is Only Office. 

Though I really wish there was a better webapp version similar to Google Docs. Only Office can run off the web but it uses a bitmap render thing which slows down it's performance a great deal.

**Comment by jcklpe** [comment]
Closing as duplicate of: https://github.com/junaid33/opensource.builders/issues/63

Office is specifically native versus webapp, but all major open source office editing webapps also have native versions (libre office for Collabora, and OnlyOffice for OnlyOffice Server)
