### ISSUE TITLE
Sentry is no longer open source

### ISSUE THREAD

**Issue by ensignavenger** [junaid33/opensource.builders#22]
Sentry is as Apache licensed, but that has changed and it is no longer open source, and should be removed.  see https://blog.sentry.io/2019/11/06/relicensing-sentry

 For an open source alternative/fork, add GlitchTip (https://glitchtip.com/)

**Comment by junaid33** [comment]
I know Sentry changed their license recently, but this app can include any application that has the source-code available and can be self-hosted. Sentry fits that criteria but if they ever remove their repo, I'll remove them.

**Comment by ensignavenger** [comment]
You can of course have whatever inclusion criteria you want, however, the title and subtitle should be changed to "source available" rather than open source- and the domain should probably be migrated also.

**Comment by ensignavenger** [comment]
You can of course choose your own selection criteria, but shouldn't the license be updated?  While you can get old versions of sentry under the Apache license, you can't get the newest under the Apache license, and I would think you would want to reflect the license accurately on the site?
