### ISSUE TITLE
meetspace

### ISSUE THREAD

**Issue by luimi** [junaid33/opensource.builders#225]
video conference and chat

**Comment by jcklpe** [comment]
@luimi  Is meetspace open source? 

What use-cases/features does it have that are different from Skype, or Zoom?

**Comment by luimi** [comment]
NVM meetspace isn't an open source.
But I found a zoom like, nodejs project based on open-easyrtc lib to video conference it's called OpenMeet

https://github.com/luimi/openMeet

**Comment by jcklpe** [comment]
I'll close and add your contribution to the existing Zoom/Skype ticket
