### ISSUE TITLE
Milvus Vector Similarity Search Engine

### ISSUE THREAD

**Issue by kateshaowanjou** [junaid33/opensource.builders#226]
Alternative to ElasticSearch for unstructured data. 
https://github.com/milvus-io

**Comment by jcklpe** [comment]
@kateshaowanjou Hi, sorry, the closed source project should be in the title of the ticket, and the comments should provide open source alternatives. You have it backwards. Please edit to follow the form correctly.

**Comment by jcklpe** [comment]
Closed with no correction
