### ISSUE TITLE
Several Non-Open Source software are included and should be removed.

### ISSUE THREAD

**Issue by ensignavenger** [junaid33/opensource.builders#23]
Here is the list of the ones I found:

Rudder (https://github.com/rudderlabs/rudder-server/blob/master/LICENSE)
FusionAuth (https://fusionauth.io/license)
Convo (https://github.com/hiconvo/api/blob/master/LICENSE)
Sentry(https://github.com/getsentry/sentry/blob/master/LICENSE)

None of these licenses are open source.  I opened a separate issue about Sentry as it is listed as Apache, and that issue includes an alternative. 

Thanks for making this resource, I hope this helps!

**Comment by ccoenen** [comment]
Why was this closed without comment? @ensignavenger has a very good point, in my opinion.
