### ISSUE TITLE
Salesforce

### ISSUE THREAD

**Issue by NGrPXL** [junaid33/opensource.builders#231]
ERP
https://www.dolibarr.org/

**Comment by jcklpe** [comment]
@NGrPXL  Hi, sorry, the closed source project should be in the title of the ticket, and the comments should provide open source alternatives. You have it backwards. Please edit to follow the form correctly.

**Comment by jcklpe** [comment]
Thank you :) @NGrPXL 

This helps reveal that this is a duplicate issue of https://github.com/junaid33/opensource.builders/issues/77

closing as duplicate
