### ISSUE TITLE
inherent structure flaws

### ISSUE THREAD

**Issue by alexanderadam** [junaid33/opensource.builders#239]
Just an example:

_Slack_, the chat of _MS Teams_ and _HipChat_ are all doing the same. But they are closed source.
Therefore there will be no result if someone is looking for an alternative for the _MS teams_ chat. Although its open source alternatives are exactly the same like those for _Slack_.

The same is true for _Google Docs_ & _MS Office 365_ or _Google Drive_ / _Dropbox_ / _Box.com_ etc.

Furthermore open source software can be an alternative for more than one "category". Because it also depends on the use case.

Imagine you just want to share your screen so others can see it. And due to your background you just know _Teamviewer_. Well, it turns out _Jitsi_ can do exactly that and you don't even necessarily have to install another client for it. But currently _Jitsi_ is just mentioned as a _Zoom_ alternative.

So users who don't know about _Zoom_, won't see on the page that _Jitsi_ would be an alternative, too.

**Comment by jcklpe** [comment]
@alexanderadam  Yeah I've been thinking about this mapping problem a lot myself. Not really sure how to deal with it exactly. 

If we were building an app from scratch, we could simply use a tag like system to do a decentralized comparison, but as we're essentially using Github tickets as an open source and low barrier to entry way of people contributing content, I'm not sure how best to deal with that. I feel like that's probably @junaid33 's call as he is the person really building the website etc. I might be able to make some contributions eventually to the website but mostly just trying to help with tickets.

**Comment by junaid33** [comment]
I've been thinking about this too and can't think of a simple, elegant solution to include other similar apps. I could make the main application an array and people can cycle thru them but search would have to be reworked. Currently, search works by flattening the main app into the alternatives so when someone searches "Shopify", all "Shopify" alternatives show up. I also plan to add categories like "Business communication" which would include Slack, Zoom, etc.

**Comment by jcklpe** [comment]
@junaid33  Would it be possible to solve the search problem using some kind of tag system? So like Shopify and all equivalents to it would carry the shopify tag, but also the tags of the other non shopify programs?

**Comment by MarkusTiede** [comment]
I've created #246 to track the idea for adding category concept.

**Comment by alexanderadam** [comment]
What's the point in having two tickets for this issue? :thinking:

**Comment by MarkusTiede** [comment]
(IMHO) to address these structure flaws there are several (maybe different) approaches being discussed here:
 - categories (containment within a category : n to 1 mapping) - pros / cons (PRs) could be further discussed in #246 
 - generic tagging (adding possibility to add arbitrary m to n mapping)

@junaid33 also proposed the category idea in #222 which is why I filed an individual issue #246. But please feel free to close if you think it's a bad idea / unnecessary.

**Comment by junaid33** [comment]
I think this should be closed now. Please check out the latest update. Multiple commercial apps can be added now.

**Comment by alexanderadam** [comment]
nice :+1:
