### ISSUE TITLE
Make cards hyperlinks

### ISSUE THREAD

**Issue by jordanliu** [junaid33/opensource.builders#26]
![image](https://user-images.githubusercontent.com/9423525/75413998-20475900-58f5-11ea-9bb6-2d590a8f96d5.png)

Make cards link to the live website for better UX

**Comment by junaid33** [comment]
Good idea. I'll start implementing this.

**Comment by jordanliu** [comment]
> Good idea. I'll start implementing this.

@junaid33 Pull request: #38
