### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by rbrixel** [junaid33/opensource.builders#296]
https://www.humhub.com/de

**Comment by jcklpe** [comment]
closed as dupe: https://github.com/junaid33/opensource.builders/issues/289

**Comment by boomtow** [comment]
What's going on with your page it's all over the place still needs alot of work

**Comment by jcklpe** [comment]
@boomtow : I'm just a volunteer but if you want to an answer to that question you'd be better off creating a new issue ticket than commenting on an unrelated issue.
