### ISSUE TITLE
vtenext

### ISSUE THREAD

**Issue by AlexRoggero** [junaid33/opensource.builders#297]
CRM with a BPM engine

**Comment by jcklpe** [comment]
@AlexRoggero  wrong format, please follow the intended format as shown by all the other issues in this repo. 

Also closing this as a dupe. If you search "CRM" in the issues you will see that there is already an issue ticket where you can add your project.

**Comment by AlexRoggero** [comment]
Ok, like this?
https://github.com/junaid33/opensource.builders/issues/77#issuecomment-629650301

Il giorno sab 16 mag 2020 alle ore 01:18 Aslan French <
notifications@github.com> ha scritto:

**Comment by jcklpe** [comment]
Yes, excellent, thank you.
