### ISSUE TITLE
Bagisto as an alternative to Shopify

### ISSUE THREAD

**Issue by prateek-webkul** [junaid33/opensource.builders#30]
E-commerce platform

https://bagisto.com/en/

https://github.com/bagisto/bagisto

**Comment by junaid33** [comment]
Added

**Comment by saurav-webkul** [comment]
Please change the deploy instruction link for Bagisto to this: [https://webkul.com/blog/laravel-ecommerce-website/](https://webkul.com/blog/laravel-ecommerce-website/
)
