### ISSUE TITLE
Freshbooks

### ISSUE THREAD

**Issue by exexzian** [junaid33/opensource.builders#305]
Invoicing and Accounting Solution

**Comment by jcklpe** [comment]
Akkaunting

**Comment by jcklpe** [comment]
@exexzian how comparable is Freshbooks to Quickbooks?   
  
We have a ticket for Quickbooks here: #258

**Comment by exexzian** [comment]
yes is comparable to Quickbooks but with the comment mentioned as frappebooks - that one is executable app - and we are looking for open source self hosted solution

**Comment by jcklpe** [comment]
Oh frappebooks isn't webased and you're looking for web based. How about akaunting? https://akaunting.com/  
  
Quickbooks and Freshbooks are both online yes? If they have the same basic functionality then I'm going to merge them into the same issues, and include a note that frappebooks is a native app.

**Comment by exexzian** [comment]
@jcklpe wow.. akaunting is cool... thanks mate

**Comment by jcklpe** [comment]
Glad I could help. I'm going to close this as a dupe
