### ISSUE TITLE
Lufi

### ISSUE THREAD

**Issue by ldidry** [junaid33/opensource.builders#311]
File transfer with E2E encryption

**Comment by jcklpe** [comment]
@ldidry  wrong format. Look at the format all the other issues in this repo follow. If not fixed in two weeks I'll close as invalid

**Comment by ldidry** [comment]
I suggest to create [issue template](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) to ease the contributions.

**Comment by jcklpe** [comment]
@ldidry I'm just a volunteer. Been meaning to do that. In the meantime, it's really not that hard for people submitting their personal projects to a platform to be promoted try and follow the requested norms in formatting.

**Comment by ldidry** [comment]
It’s not hard but there is no indication that there is no more things needed.
Adding `+%0A<!--+That’s+all%2C+you+don’t+need+to+write+more+-->` to the URL we are redirected from https://opensource.builders/requests would be a good thing.

BTW, I changed my issue, why did you close it?

**Comment by jcklpe** [comment]
@ldidry  You didn't edit your issue. The closed source goes in the title, the open source goes in the description, as all other request issues in this repo show. I'll reopen when you edit it to be correct format. I do not personally know enough about your project to edit a suitable closed source alternative myself.

**Comment by ldidry** [comment]
Sorry, this format wasn’t clear to me. I created a [new issue](https://github.com/junaid33/opensource.builders/issues/316).
