### ISSUE TITLE
Mautic

### ISSUE THREAD

**Issue by thanisch** [junaid33/opensource.builders#318]
CRM / Marketing Platform

Definitely misses in this list as an open source alternative to Salesforce and/or MailChimp. :)

https://github.com/mautic/mautic

**Comment by thanisch** [comment]
https://github.com/mautic/mautic

**Comment by jcklpe** [comment]
@thanisch Sorry this is incorrect format. Closed source in the title, open source in the comments. Also a dupe of #77 unless you would like to help define a distinction between what it offers and the other open source CRMs listed there. I will also add mautic to the list on that ticket. Thank you for contributing :)
