### ISSUE TITLE
Jami

### ISSUE THREAD

**Issue by francisgernet** [junaid33/opensource.builders#327]
Category : Communication (video)
site : https://jami.net/
licence : GPLv3

**Comment by jcklpe** [comment]
Wrong format. Please look at the other issue tickets. Closed source goes in the issue ticket title and the alts go on the description/comments

**Comment by francisgernet** [comment]
Site usage is very poorly documented.
IMHO, it is useless to enrich it, it is promised to stagnate soon.Prefer https://alternativeto.net/. It is not only OpenSource, but you can easily add references.

**Comment by jcklpe** [comment]
@francisgernet Yeah, I'm just a volunteer.
