### ISSUE TITLE
Luckysheet

### ISSUE THREAD

**Issue by Dushusir** [junaid33/opensource.builders#336]
online spreadsheet

**Comment by Dushusir** [comment]
According to the official website, this spreadsheet plugin is a pure front-end online table similar to Excel, with powerful functions, simple configuration and completely open source.

Official website link:

Luckysheet official website 
https://mengshukeji.github.io/LuckysheetDocs/

Online Demo 
https://mengshukeji.github.io/LuckysheetDemo/

**Comment by jcklpe** [comment]
@Dushusir  Hey thanks for contributing. You've got the wrong format though. The open source software alternatives go in the comments and description of the ticket, and the closed source alternatives go in the title. Please reformat according to the pattern, thanks.

**Comment by jcklpe** [comment]
Closed as not fixed
