### ISSUE TITLE
Shutter Encoder Free video|image|audio converter for all platforms

### ISSUE THREAD

**Issue by paulpacifico** [junaid33/opensource.builders#343]
Shutter Encoder is a free video, audio and image converter based on FFmpeg and other tools.

It has been designed by video editors in order to be as accessible and efficient as possible.

It's a swiss knife tool for any video editor.

Here is the link to website & download: https://www.shutterencoder.com
And GitHub: https://github.com/paulpacifico/shutter-encoder

![SocialBanner](https://user-images.githubusercontent.com/46673657/90960497-3c8e1200-e4a2-11ea-973a-9a38a5198f07.png)

**Comment by jcklpe** [comment]
@paulpacifico  please put the closed source project in the title and the open source alternative in the comments/description. If you look at the rest of the items in this github issue tickets log you'll see how they follow this format. Please follow the format.

**Comment by jcklpe** [comment]
Closing as invalid.
