### ISSUE TITLE
Psono

### ISSUE THREAD

**Issue by IVRYSimon** [junaid33/opensource.builders#384]
Password Management

**Comment by matbrgz** [comment]
BitWarden
bitwarden.com
https://github.com/bitwarden

**Comment by jcklpe** [comment]
@IVRYSimon : wrong format. Closed source applications go in the title, open source alternatives go in the comments. Also we already have a ticket open to cover password managers. You should add your recommendation here instead: [https://github.com/junaid33/opensource.builders/issues/161](https://github.com/junaid33/opensource.builders/issues/161)  
  
Closing as dupe.
