### ISSUE TITLE
LemonLDAP::NG

### ISSUE THREAD

**Issue by coudot** [junaid33/opensource.builders#395]
Free WebSSO software providing CAS, SAML and OpenID Connect support.
https://lemonldap-ng.org/
https://gitlab.ow2.org/lemonldap-ng/lemonldap-ng
https://github.com/LemonLDAPNG/

**Comment by jcklpe** [comment]
@coudot Please follow the correct format. See the rest of the tickets in the repo to see correct format. Marking as invalid and will close if not fixed within 30 days

**Comment by coudot** [comment]
Description updated

**Comment by jcklpe** [comment]
@coudot   You need to put the closed source thing that the open source is an alternative to in the title.

**Comment by coudot** [comment]
Ok, so I added a comment in #242.

Hope this is the correct way.

**Comment by jcklpe** [comment]
@coudot  Thank you! this is excellent! Always exciting to see new SSO providers added to the list :)
