### ISSUE TITLE
Zulip logo is outdated

### ISSUE THREAD

**Issue by timabbott** [junaid33/opensource.builders#397]
Thanks for building this site!

Can you update the Zulip logo?  The version you have appears to be an unusual variant of our old logo (replaced a year ago).  You can get current assets here: https://github.com/zulip/zulip/tree/master/static/images/logo 

Also, you might as well update the website to zulip.com, since zulip.org just redirects to there these days.

**Comment by kogeletey** [comment]
Yes of course. Now let's do

**Comment by jcklpe** [comment]
Closing as fixed.
