### ISSUE TITLE
Logo of Sylius not working

### ISSUE THREAD

**Issue by reyostallenberg** [junaid33/opensource.builders#40]
https://sylius.com/wp-content/uploads/2019/04/sylius-brand-book-v1.0.pdf

**Comment by junaid33** [comment]
Could you send a screenshot? It showing up fine on my end:

<img width="480" alt="Screen Shot 2020-02-28 at 11 29 24 AM" src="https://user-images.githubusercontent.com/34615258/75570840-a068de00-5a1d-11ea-947f-ed826d386943.png">

**Comment by jordanliu** [comment]
Same on my end
![image](https://user-images.githubusercontent.com/9423525/75571038-66e8a080-5a26-11ea-8281-6c0d89a89688.png)

**Comment by reyostallenberg** [comment]
In Brave it looks like 
![image](https://user-images.githubusercontent.com/3579090/75604380-4da02c80-5ad8-11ea-8375-b5b0fd4ac79c.png)

But if I choose 'Open image in new tab' I get the correct image, very strange.
I think Brave is blocking licdn.com for privacy reasons

**Comment by junaid33** [comment]
Ok it seems a PR has fixed this.
