### ISSUE TITLE
Focalboard

### ISSUE THREAD

**Issue by mdll** [junaid33/opensource.builders#408]
Focalboard is an open source, self-hosted alternative to Trello, Notion, and Asana.

It's a project management tool that helps define, organize, track and manage work across teams, using a familiar kanban board view.

URL: https://www.focalboard.com
GitHub: https://github.com/mattermost/focalboard

**Comment by jcklpe** [comment]
@mdll : hey sorry could you follow the format of the other tickets? 

Open source stuff goes in the comments but the title of the ticket should be what it is an alternative too. 


Also there's already existing tickets for Trello, Notion, and Asana so unless there is a particularly unique use case then this should be closed as dupe. 

I'm going to mark as "invalid" and will close as invalid and/or dupe if not fixed within 30 days and given a unique "closed source alternative" reason. Thank you.

**Comment by jcklpe** [comment]
Over thirty days with no update. Closing as invalid.
