### ISSUE TITLE
Salesforce & SAP

### ISSUE THREAD

**Issue by rorosan** [junaid33/opensource.builders#412]
Flectrahq is an opensource alternative to salesforce and Sap, written in python and with a much more permisse licence than Odoo, in which it's first committers were involded.
The website ; https://flectrahq.com/
The project is hosted on gitlab.com : https://gitlab.com/flectra-hq/flectra
Thanks for your work on this project ! This is a goldmine !

**Comment by jcklpe** [comment]
Closing as a duplicate: https://github.com/junaid33/opensource.builders/issues/77
