### ISSUE TITLE
cPanel

### ISSUE THREAD

**Issue by Lecquio** [junaid33/opensource.builders#42]
Web Hosting Control Panel

**Comment by Lecquio** [comment]
Alternatives:
vestacp
ispconfig
Usermin

**Comment by johnnyq** [comment]
HestiaCP - https://hestiacp.com/

This basically supersedes VestaCP

**Comment by junaid33** [comment]
Added

**Comment by mentec** [comment]
Webuzo : https://www.webuzo.com/
