### ISSUE TITLE
Milanote

### ISSUE THREAD

**Issue by CGPipeliner** [junaid33/opensource.builders#423]
Milanote is an easy-to-use tool to organize your ideas and projects into visual boards.
https://milanote.com/

Miro is a commercial alternative. But I like that you can create columns and add links, images, videos, GIF and mars, crosses and everything which makes it vers visual. You can even treate kanban boards.

**Comment by jcklpe** [comment]
@CGPipeliner : Milanote does not appear to be open source from what I can tell and neither is Miro. Are you requesting an open source alternative to these apps? How does the milanote functionality differ from a kanban board as listed in this ticket? #422   
  
I'm marking this as invalid. If there isn't an update within 30 days I'm going to close the ticket as invalid.

**Comment by CGPipeliner** [comment]
I requested an open source alternative. Milanote doesn't have a raster and it isn't a kanban board. Its a whiteboard where you can add many elements to it: https://www.youtube.com/watch?v=y4Aj3gPXNs4

It's the most visual tool I've seen and I am curiuos if there is an open source project like this one.

**Comment by jcklpe** [comment]
@CGPipeliner  : is it like Miro or Mural? https://www.g2.com/products/miro/competitors/alternatives

**Comment by jcklpe** [comment]
Actually looks like we do have an existing ticket for Miro. I will close this ticket as a dupe, and expand the original ticket for greater clarity and breadth.
