### ISSUE TITLE
Shopify / BigCommerce

### ISSUE THREAD

**Issue by ojohnny** [junaid33/opensource.builders#440]
E-commerce platform

Repository: https://github.com/vendure-ecommerce/vendure
Website: https://www.vendure.io/

**Comment by jcklpe** [comment]
@ojohnny : Wrong format. Closed source goes in title, open source goes in the comments. Marking this as invalid. If not reformatted within 30 days will close as invalid. Thanks.

**Comment by ojohnny** [comment]
@jcklpe Done.  But to be clear, this was the pettiest response I have ever had to an improvement suggestion ever.  This rule does not even seem to be documented on the "Adding a new request" page.

I wont be adding any more suggestions here in the future.

**Comment by junaid33** [comment]
@ojohnny I don't think @jcklpe was trying to be petty. Many people are confused about how to create issues and create it like you have. The website not mentioning the right way is on me and I apologize for that. Aslan helps me maintain this repo so please put the brunt of the blame on me. Opensource.builders 2.0 is on the horizon and we will be using an actual CMS so most of these issues will subside. Happy holidays!

**Comment by ojohnny** [comment]
@junaid33 I don't think anyone was being intentionally petty, and I'm sorry if my words offended.  I just vented my frustration as a first-time submitter.

I can't see how closing legitimate requests as "invalid for not following rules you could not possibly have known about" is a good on-boarding experience.

I don't even think the ticket was missing any information either since I wrote that it was for the "E-commerce platform" section of the site (I can only see one of those?  "E-commerce platform" was also written in the request form placeholder).  It was the act of closing a request when it did not actually miss any vital information that felt petty.  The rule of "requiring closed source counterpart in the title" would make more sense if I was asking for a new section on the site, which I had no intention of doing.

Suggestions for improvements for handling first-time submitters:
1. If the format of the requests are vital to the point of closing as invalid if a format is not being followed, please consider adding an issue template to Github.
2. Don't make the first reply read as the submitter is to blame for things outside the submitters control.  Ideally I think a response like "Is this an alternative for X?  If so, please rename the title to X." would feel more welcoming.  If this level of detail is not possible (due to too many requests etc) I think a link to an official request guideline page  would also help (because I as a submitter should probably have read those before submitting, thus it was in my control).

**Comment by jcklpe** [comment]
We already have a Shopify page, apologies I will have to close this as a dupe. See: https://github.com/junaid33/opensource.builders/issues/58

**Comment by jcklpe** [comment]
Also @ojohnny : I am just a volunteer pruning duplicates and such. Me marking your ticket invalid for being formatted incorrectly is not a slander on your character or accusation against you. There was nothing in my original statement about "blaming" anyone. 

Secondly, you are not paying me. Neither is @junaid33  You are not owed customer service. This is a free project. You are not speaking to your underling. Please treat other people with the same kind of peer respect you would like to be treated with, rather than like some Karen demanding to see the manager.

**Comment by ojohnny** [comment]
To be clear, I don't expect "customer service".  I am also in no way affiliated with any of the projects I was suggesting.

I am just an advocate for open source software, who just thought he could contribute to a list of open source alternatives to closed source software.

It seems the process of submitting suggestions for these open source alternatives could be improved.   I submitted a suggestion in good faith, which is now closed and probably forgotten because I simply could not understand the internal structure of this issue tracker.  I'm not even sure if I was supposed to add my suggestion as a comment on the linked issue which this was supposedly closed as a duplicate of.

Be sure I mean well.  Do with this information as you wish.  I just want to highlight that the first impression I got would likely scare more people away.  Owners and volunteers of this project alike could do well to think about this if you want more volunteers in the future.  I don't blame you if you do not want this, it is your project after all.

**Comment by jcklpe** [comment]
@ojohnny : thank you for the feedback. I agree that the process for contribution could be improved. 

If I can give some context, a space for empathy here: 

We have dozens of people adding tickets to this project, some through the website, some through github. Many people are just spamming every available open source list they can with their personal project, half of them are unfinished messes. We don't discriminate on the quality of projects, we just ask that people do the minimum of submitting stuff in correct format. People who are interested in submitting stuff usually have no problem following submission guidelines, checking the issue tickets for dupes before submitting, that sort of thing. 

I get that this submission process for this thing is bad.  I'm a designer who knows enough development to get myself in trouble, so my ability to fix these issues is limited. We've had some discussions on how we can improve these issues (CMS, no CMS, using github etc etc). This project has not seen major structural changes to code in several years, so at this point it's sort of in maintenance mode and the vast majority of useful information isn't even on the website, it's just buried in these tickets. Occasionally people will make a pull request to add information to the website and I pretty much just check it for malicious code and send it on through. 

I'd love to see a more robust UX. Thank you for your contribution, I hope the rest of your holiday season is merry.
