### ISSUE TITLE
Deployer

### ISSUE THREAD

**Issue by malteschlueter** [junaid33/opensource.builders#459]
A deployment tool written in PHP with support for popular frameworks out of the box.

License: MIT

https://github.com/deployphp/deployer

**Comment by jcklpe** [comment]
@malteschlueter : wrong format. Please format correctly. This ticket has been marked as invalid and if not corrected in the next 30 days it will be closed.   
  
The correct format is: Close source in title: Open source in comments of ticket.

**Comment by malteschlueter** [comment]
I don't know a close source of an deployment tool. I thought it would be useful for people who searching for a deploy tool not for cloud services.
