### ISSUE TITLE
Commercial hospitality solutions: Cloudbeds/Oracle Hospitality/nobeds/Hotello/Hotelogix

### ISSUE THREAD

**Issue by abhishek-webkul** [junaid33/opensource.builders#480]
QloApps is an open-source alternative to above commercial solutions.

Website: https://qloapps.com/
Repo: https://github.com/webkul/hotelcommerce
License: OSL 3.0
Language: PHP

**Comment by jcklpe** [comment]
Thank you for following the format! This is great.

**Comment by abhishek-webkul** [comment]
Any updates on this request?

**Comment by jcklpe** [comment]
@abhishek-webkul : We use the requests to track stuff, we don't use it to make requests for the web site itself. Basically the github issues act as a proto-cms. You are more than welcome to make a pull request though! :)
