### ISSUE TITLE
Float UI

### ISSUE THREAD

**Issue by alien-marsx** [junaid33/opensource.builders#486]
Float UI - free web development tool for easy creation of modern, responsive websites with sleek design, even for non-designers

**Comment by jcklpe** [comment]
@alien-marsx  this is the wrong format. Closed source goes in title, open source goes in the ticket comments. I'm marking this as invalid and will close it if not fixed within 30 days. Thank you!

**Comment by alien-marsx** [comment]
Hey, Sorry for this mistake:
MarsX and Float UI are open source projects, here are the links to their
GitHub repositories:
https://github.com/MarsX-dev
https://github.com/MarsX-dev/floatui

How can I correct the application?
Thanks!

**Comment by jcklpe** [comment]
@alien-marsx you need to put the closed source product they are an alternative to in the ticket Title.

**Comment by jcklpe** [comment]
@alien-marsx Your project appears to be a component library? This repo only tracks self hostable open source products, not code library tools I'm afraid. Unless I am mistaken, please correct. Thank you.

**Comment by jcklpe** [comment]
requested changes were not made. closing as invalid.
