### ISSUE TITLE
https://github.com/projectsveltos

### ISSUE THREAD

**Issue by gianlucam76** [junaid33/opensource.builders#487]
Sveltos is an open source project to manage Kubernetes add-ons. It automatically discovers ClusterAPI  powered clusters and allows to easily register any other cluster (like GKE). Then, it seamlessly manages Kubernetes add-ons across all your clusters.

But that's not all. Sveltos comes loaded with features like event-driven add-on deployment (using Lua scripts), configuration drift detection, and multi-tenancy to easily manage permissions for tenant admins. Even preview changes with a dry run and rollback configurations with ease.

**Comment by jcklpe** [comment]
Wrong format. Closed source goes in title and open source goes in comments. Marked invalid. If not fixed within 30 days, ticket will be closed.

**Comment by jcklpe** [comment]
requested changes were not made. closing as invalid.
