### ISSUE TITLE
invalid

### ISSUE THREAD

**Issue by stefan-gorules** [junaid33/opensource.builders#492]
Open-source business rules engine

**Comment by stefan-gorules** [comment]
Homepage: https://gorules.io
ZEN Engine - used for evaluation - https://github.com/gorules/zen
JDM Editor - https://github.com/gorules/jdm-editor

**Comment by jcklpe** [comment]
@stefan-gorules this is in the wrong format. Closed source goes in the ticket title, and the suggested alternatives go in the comments. I'm marking this as invalid, and will close after 30 days if not amended. Thank you!

**Comment by jcklpe** [comment]
Closing as invalid.
