### ISSUE TITLE
eXo Platform

### ISSUE THREAD

**Issue by brahimjaouane** [junaid33/opensource.builders#499]
[**eXo Platform**](https://www.exoplatform.com/) is an **open source digital workplace solution** that helps you build, grow and engage your community. It has a range of powerful community tools designed to improve internal communications, knowledge management and social networking. eXo platform also enables you to create your own community platform so you can make informed and impactful business decisions.

**Comment by jcklpe** [comment]
@brahimjaouane  Wrong format. Open source alternative goes in the comments, the closed source goes in the title. Marking as invalid. If not corrected within 30 days, I will close as invalid. Thank you.

**Comment by brahimjaouane** [comment]
Open source alternative

**Comment by jcklpe** [comment]
@brahimjaouane What is the name of the closed source software this is an alternative to?

**Comment by jcklpe** [comment]
Closing as invalid
