### ISSUE TITLE
Authentik

### ISSUE THREAD

**Issue by vinii8817** [junaid33/opensource.builders#500]
Authentik (https://goauthentik.io)

Auth (Similar Auth0)

Opensource with OpenID/oauth2 , SAML , LDAP, Radius and Proxy.

**Comment by jcklpe** [comment]
@vinii8817  Wrong format. Open source alternative goes in the comments, the closed source goes in the title. Marking as invalid. If not corrected within 30 days, I will close as invalid. Thank you.

**Comment by jcklpe** [comment]
Closing as duplicate: https://github.com/junaid33/opensource.builders/issues/242
