### ISSUE TITLE
Impler

### ISSUE THREAD

**Issue by chavda-bhavik** [junaid33/opensource.builders#501]
# Description
- Open-Source Data Import Platform for developers
- Enables developers to build rich, embeddable data-import experience in minutes.

# Links
- [Website](https://impler.io/)
- [LinkedIn](https://linkedin.com/company/implerofficial)

# Signup
- [Start Now, It's free](https://web.impler.io)

**Comment by jcklpe** [comment]
@chavda-bhavik   
  
Wrong format. Open source alternative goes in the comments, the closed source goes in the title. Marking as invalid. If not corrected within 30 days, I will close as invalid. Thank you.

**Comment by jcklpe** [comment]
Closing as invalid.
