### ISSUE TITLE
Postman 

### ISSUE THREAD

**Issue by shreya-gr** [junaid33/opensource.builders#503]
Alternative : 
Firecamp is opensource API platform that helps developers in building APIs faster.  Opensource Postman/insomnia alternative. 

Firecamp GitHub : https://github.com/firecamp-dev/firecamp
Firecamp web : https://firecamp.dev

**Comment by jcklpe** [comment]
Closed as duplicate: https://github.com/junaid33/opensource.builders/issues/97
