### ISSUE TITLE
Rannkly

### ISSUE THREAD

**Issue by Rannkly-Software** [junaid33/opensource.builders#511]
Rannkly is an AI driven software which helps manage your all reviews on a single dashboard. With the help of Rannkly's Best Online Reputation management Tool, a business can build and grow their online presence and manage all the reviews from different platforms in a single dashboard.
![Untitled design](https://github.com/junaid33/opensource.builders/assets/156656599/6ce228bf-4924-4a54-9416-1cda68c56914)

**Comment by jcklpe** [comment]
Incorrect format. Closing as non compliant.
