### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by Sssssawdsaswad** [junaid33/opensource.builders#53]
Smart home integration management

**Comment by quostta** [comment]
[Snips](https://snips.ai/)
[Mycroft](https://mycroft.ai/)
[Gladys](https://gladysassistant.com/en/)
[Home Assistant](https://www.home-assistant.io/)

**Comment by jhollowe** [comment]
[Home Assistant](https://www.home-assistant.io/) has an amazing community and can control almost anything

**Comment by jcklpe** [comment]
@Sssssawdsaswad Hi, sorry, the closed source project should be in the title of the ticket, and the comments should provide open source alternatives. You have it backwards. Please edit to follow the form correctly.

**Comment by jcklpe** [comment]
Closing as invalid.
