### ISSUE TITLE
Shopify

### ISSUE THREAD

**Issue by alexanderadam** [junaid33/opensource.builders#59]
- https://github.com/solidusio/solidus
- https://solidus.io/
- https://www.youtube.com/channel/UCiFcxyt11T6QIIDPk2w0Jjw/videos

**Comment by jcklpe** [comment]
@alexanderadam So you do correctly have the closed source software in the title and it is clear which is the closed source and which is the open source one, but from what I understand, the title for requests should be just the closed source alternative, allowing for the issue thread to be open for the discussion of multiple alternatives, and to prevent as many duplicate issues being made as possible.

**Comment by jcklpe** [comment]
Closing as duplicateto https://github.com/junaid33/opensource.builders/issues/58

If you'd like this added to that request please add information there as a comment. I'm trying to help consolidate discussion and duplication in the issue tickets.
