### ISSUE TITLE
Zoho

### ISSUE THREAD

**Issue by jitenagarwal19** [junaid33/opensource.builders#81]
ERP Solutions

**Comment by spannella** [comment]
Zoho’s email client / contacts management would be awesome

**Comment by jewelhuq** [comment]
Zoho Subscription, Books

**Comment by jcklpe** [comment]
@jitenagarwal19 , @spannella , @jewelhuq 

Is this a duplicate of: https://github.com/junaid33/opensource.builders/issues/77

I don't use Zoho, and I'm not super familiar with the ERP space.

**Comment by jcklpe** [comment]
Closing this as dupe for #77
