### ISSUE TITLE
Pipedrive

### ISSUE THREAD

**Issue by gEndelf** [junaid33/opensource.builders#89]
CRM for sales

**Comment by mjjzf** [comment]
[Vtiger](http://vtiger.com) and [SugarCRM](http://sugarcrm.com) are both open source.
They both have mobile clients, too.

**Comment by mjjzf** [comment]
Merge with #82 ?

**Comment by gEndelf** [comment]
@mjjzf SugarCRM completed support CE version

**Comment by jcklpe** [comment]
I've also read about Odoo as a CRM alternative but don't know much about it as I've never used it myself.

**Comment by jcklpe** [comment]
I'm not clear on the differences between CRMs and ERPs but this appears to be a duplicate of https://github.com/junaid33/opensource.builders/issues/77

@gEndelf please merge if appropriate.
